version: '3'
services:
  rasa:
    image: rasa/rasa:3.6.20-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command: 
      - run
  
  action-server:
    image: rasa/rasa-sdk:3.0.0
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
  
  mongo-db:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017